.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH export 1  "export " 
.SH NAME
export \- Export the public key of a key file (armored, or ASCII85 for DNS TXT)
.SH SYNOPSIS
\fBexport\fR [\fB\-k\fR|\fB\-\-key\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-\-txt\fR] [\fB\-\-no\-passphrase\fR] [\fB\-\-passphrase\-file\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Export the public key of a key file (armored, or ASCII85 for DNS TXT)
.SH OPTIONS
.TP
\fB\-k\fR, \fB\-\-key\fR \fI<KEY>\fR
Path to the secret key file (.hskey)
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<OUTPUT>\fR
Write the public key to this file
.TP
\fB\-\-txt\fR
Output the ASCII85 public key as DNS TXT character\-strings (max 255 bytes each)
.TP
\fB\-\-no\-passphrase\fR
Use an empty passphrase (no prompt)
.TP
\fB\-\-passphrase\-file\fR \fI<PASSPHRASE_FILE>\fR
Read the passphrase from a file (first line)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
