.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH verify 1  "verify " 
.SH NAME
verify \- Verify signed blocks in an HTML file
.SH SYNOPSIS
\fBverify\fR [\fB\-k\fR|\fB\-\-key\fR] [\fB\-\-ignore\-tls\-errors\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE|URL\fR> 
.SH DESCRIPTION
Verify signed blocks in an HTML file
.SH OPTIONS
.TP
\fB\-k\fR, \fB\-\-key\fR \fI<KEY>\fR
Require blocks to be signed with this armored public key
.TP
\fB\-\-ignore\-tls\-errors\fR
Skip TLS certificate validation when verifying a URL
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE|URL\fR>
HTML file or URL to verify
